account/web/urls.py
from django.urls import path

from account.web.views import (account_view, edit_account_view,)

app_name = 'account'

urlpatterns = [
	path('',account_view,name= "account"),
	path('<user_id>/', account_view, name="view"),
	path('<user_id>/edit/', edit_account_view, name="edit"),
]

main/urls.py

from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.web.views import (register_view,logout_view,login_view,account_view,account_search_view )

import debug_toolbar
from django.conf import settings
from django.conf.urls import url
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


admin.site.site_header = 'موقع الإشباح'
admin.site.site_title = 'الأشباح للإتصالات'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('homeApp.urls')),     
    path('cash/',include('vcashApp.urls')),
    path('follow/',include('FollowUpApp.urls')),
    
    path('customers/',include('customers.urls')),
    path('transactions/',include('transactions.urls')),

    path('sellers/',include('sellersApp.urls')),
    path('store/',include('storeApp.urls')),
    path('productsSeles/',include('productsSelesApp.urls')),
    path('fawrySeles/',include('fawrySelesApp.urls')),

    path('fawryCodes/',include('fawryCodesApp.urls')),
    path('dataEltogar/',include('dataEltogarApp.urls')),
    path('code/',include('fawryCodesApp.api.urls','fawry_api')),
    path('shakawa/', include('shakawaApp.urls')),

    # region ACCOUNTS
    path('account/', include('account.urls')),
    path('register/',register_view,name= "register"),
    path('logout/',logout_view,name= "logout"),
    path('login/',login_view,name= "login"),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),name='password_reset_complete'),
    path('search/', account_search_view, name="search"),
    # endregion ACCOUNTS
]


if settings.DEBUG: 
    schema_view = get_schema_view(
   openapi.Info(
      title=admin.site.site_title,
      default_version='v1',
      description="Test description",
      terms_of_service=settings.ALLOWED_HOSTS[0],
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
    )
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls)),
        # Swagger
        url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
        url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
        url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    ]

templates/snippets/base_css.html
{% load static %}
<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Local css files relative -->
<link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
<style type="text/css">
	.wrapper{
		min-height: 100vh;
		height:100%;
	}
	body{
		font-family: 'Tajawal', sans-serif;
		background-color: #f2f2f2;
		font-weight: 380;}
	head{
		font-family: 'Tajawal';
		font-weight: 380;
	}
	footer{
		font-family: 'Tajawal', sans-serif;
		font-weight: 380;
	}
	
	svg{
	width: 120px;
	height: auto;
	}

	#loading{
		text-align: center;
	margin-top: 200px;}
	#box_message_success{ display: none;}
	#box_message_danger{ display: none;}
	#success{ display: none;}

	:root{
		--main-background-color: #f2f2f2;
		--dark-background-color: #a2a2a2;
		--secondary-text-color: #808080;
		--light-primary-text-color: #0080ff;
	}
</style>

templates/snippets/base_js.html
{% load static %}
<!-- LOCAL js relative -->
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'main/popper-min.js' %}"></script>
<script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/fontawsome-all.min.js' %}"></script>
<script src="{% static 'main/myjs.js' %}"></script>
<script type="text/javascript">
  // --------------- Start page loading ------------------\\

  // Function for adding User data and removing loading animation
  var replace_data = function(){
      $('#success').show();
      $('#loading').hide();    }

  // AJAX call when page has loaded
  $(document).ready(function(){
    // datatable place here we was wotre
      $.ajax({
          url: '',
          data: {
              'name': 'FOO'
          },
          data_type: 'html',
          success: function(data){
              replace_data(data);
          }
          });
          });

  // --------------- End page loading ------------------\\

  </script>
{% block script %}
{% endblock script %}

templates/snippets/footer.html
{% load static %}
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
	<p class="m-auto">Developerd By: Mohamed Arafa | 2021</p>
</div>
<!-- End Footer -->

templates/snippets/header.html
{% load static %}

<!-- Header navbar bg-light -->
<div class="d-flex flex-column flex-lg-row p-3 px-md-4 bg-white border-bottom shadow-sm">
	{% if request.user.is_authenticated %}
	<button type="button" id="sidebarCollapse" class="btn btn-primary">
		<i class="fa fa-bars"></i>
		<span class="sr-only">Toggle Menu</span>
	  </button>
	  <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <i class="fa fa-bars"></i>
	  </button>
	{% endif %}

	  
	<!-- MEDIUM+ SCREENS -->
	<div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
		<h5 class="mr-3 font-weight-normal justify-content-start">
			<a class="p-2 text-dark" href="{% url 'home' %}">قرطبة للإتصالات</a>
		</h5>
		<form class="search-bar justify-content-start">
			<input type="text" class="form-control" name="q" id="id_q_large" placeholder="Search...">
		</form>
		{% if request.user.is_authenticated %}
<!-- region NavBar -->
<nav class="navbar-expand-lg navbar-light">
	<div class="container-fluid">
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="nav navbar-nav ml-auto">
		  <li class="nav-item active">
			  <a class="nav-link" href="#">الرئيسية</a>
		  </li>
		  <li class="nav-item">
			  <a class="nav-link" href="#">العملاء</a>
		  </li>
		  <li class="nav-item">
			  <a class="nav-link" href="#">المناديب</a>
		  </li>
		  <li class="nav-item">
			  <a class="nav-link" href="#">التحويلات</a>
		  </li>
		  <li class="nav-item">
			  <a class="nav-link" href="#">داتا التجار</a>
		  </li>
		</ul>
	  </div>
  </div>
</nav>
{% endif %}	
  <!-- endregion NavBar -->
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
					<div class="dropdown dropleft show p-2">
						<div class="d-flex flex-row">

							<div class="btn-group dropleft">
								<div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3" id="id_chat_notification_dropdown_toggle" data-toggle="dropdown">
									<span id="id_chat_notifications_count" class="notify-badge"></span>
									<span class="d-flex material-icons notifications-material-icon m-auto align-items-center">chat</span>
									<div class="dropdown-menu scrollable-menu" aria-labelledby="id_chat_notification_dropdown_toggle" id="id_chat_notifications_container">
											
									</div>
								</div>
							</div>

							<div class="btn-group dropleft">
								<div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3" id="id_notification_dropdown_toggle" data-toggle="dropdown" onclick="setGeneralNotificationsAsRead()">
									<span id="id_general_notifications_count" class="notify-badge"></span>
									<span class="d-flex material-icons notifications-material-icon m-auto align-items-center">notifications</span>
									<div class="dropdown-menu scrollable-menu" aria-labelledby="id_notification_dropdown_toggle" id="id_general_notifications_container">										
									</div>
								</div>
							</div>

							<div class="btn-group dropleft">
								<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{% static 'codingwithmitch/dummy_image.png' %}" alt="codingwithmitch logo" width="40" height="40">
								<div class="dropdown-menu" aria-labelledby="id_profile_links">
									<a class="dropdown-item" href="#">Account</a>
									<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
								</div>
							</div>
						</div>
						
					</div>
				{% else %}
				<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
					<a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a> 
				{% endif %}	
			</nav>
		</div>
	</div>
	<!-- END MEDIUM+ SCREENS -->
	
	<!-- SMALL SCREENS -->
	<div class="d-flex d-md-none flex-column my-auto align-items-center">
		<h5 class="font-weight-normal">
		<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		</h5>
		<form class="search-bar justify-content-start" >
			<input type="text" class="form-control" name="q" id="id_q_small" placeholder="Search...">
		</form>
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
				<div class="dropdown dropleft p-2 mt-2">
					<div class="d-flex flex-row">
						<div class="btn-group dropleft">
							<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" alt="codingwithmitch logo" width="40" height="40">
							<div class="dropdown-menu" aria-labelledby="id_profile_links">
								<a class="dropdown-item" href="{% url 'account:view' user_id=request.user.id %}">Account</a>
								<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
							</div>
						</div>
					</div>
				</div>
				{% else %}
					<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
					<a class="btn btn-outline-primary m-2" href="{% url 'register' %}">Register</a>
				{% endif %}	
			</nav>
	  	</div>
	</div>
	<!-- END SMALL SCREENS -->
</div>

<script type="text/javascript">
	function executeQuery() {
		var query = ""
		query = document.getElementById('id_q_small').value;
		if (query == ""){
			query = document.getElementById('id_q_large').value;
		}
	    window.location.replace("{% url 'search' %}?q=" + query)
	    return false
	}
</script>

<!-- 
<button type="button" id="sidebarCollapse" class="btn btn-primary">
                  <i class="fa fa-bars"></i>
                  <span class="sr-only">Toggle Menu</span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
    
<nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Add Patient</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Patient List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Print Prescription</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Medically compromised Patient</a>
                    </li>
                  </ul>
                </div>
			</div>
		</nav>

 -->

templates/snippets/sidebar.html
{% load static %}
{% if request.user.is_authenticated %}
<nav id="sidebar">
    <div class="p-4 pt-5">
      <a href="#" class="img logo rounded-circle mb-5" style="background-image: url({% static 'images/logo.png' %});"></a>
      <ul class="list-unstyled components mb-5">
        <li class="active" >
            <a href="{% url 'create' %}">(تجريبى) إضافة عميل</a>
        </li>
        
        <li >
          <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">قائمة العملاء</a>
          <ul class="collapse list-unstyled" id="pageSubmenu2">
            <li>
              <a href="{% url 'showList' %}"> (تجريبى)قائمة العملاء</a>
            </li>
            <li>
                <a href="{% url 'customers_manadeep' %}">قائمة عملاء المناديب</a>
            </li>
          </ul>
       </li>

      <li>
        <a href="{% url 'transactions' %}">تحويلات المناديب</a>
    </li>
        <li>
          <a href="#pageSubmenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">داتا التجار</a>
          <ul class="collapse list-unstyled" id="pageSubmenu3">
            <li>
                <a href="{% url 'table' %}">جدول داتا التجار</a>
            </li>
            <li>
                <a href="{% url 'analys' %}">تحليل داتا التجار</a>
            </li>
          </ul>
        </li>
      
        
<!-- 	          <li>
          <a href="#">Print Prescription</a>
        </li>
        <li>
          <a href="#">Medically compromised Patient</a>
        </li> -->
      </ul>

      <div class="footer">
            <!-- <p>developed by mohamed arafa</p> -->
          </div>

    </div>
  </nav>
{% endif %}